version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    volumes:
      - .:/app
    entrypoint: /app/entrypoint.sh
    depends_on:
      - db
  db:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_DB: "geo_data"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      CLIENT_ENCODING: UTF8
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
